controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

hello:
    path: /hello
    defaults: {
        _controller: App\Controller\HelloController::hello
    }