controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

hello:
    path: /hello
    defaults: {
        _controller: App\Controller\HelloController::hello
    }

create:
    path: /create
    defaults: {
        _controller: App\Controller\HelloController::create
    }

patch:
    path: /patch
    defaults: {
        _controller: App\Controller\HelloController::patch
    }

delete:
    path: /delete
    defaults: {
        _controller: App\Controller\HelloController::delete
    }

get:
    path: /get
    defaults: {
        _controller: App\Controller\HelloController::get
    }